### ISSUE TITLE
Interface generator sensitive to case of EXTERNAL statement and generates incorrect interfaces

### ISSUE THREAD

**Issue by gdcarver** [metomi/fcm#175]
There's a bug in FCM's interface generator regarding the use of the `EXTERNAL` statement. The external statement is missing from the generated interface if the original source uses upper case or some instances of mixed case.

e.g. a test case:
```fortran
subroutine test4(proga, progb)
EXTERNAL PROGA,PROGB
end subroutine
```

will generate an interface file without the external statement. Whereas, this works:

```fortran
subroutine test1(proga, progb)
external proga,progb
end subroutine
```

This also works:
```fortran
subroutine test7(proga,progb)
EXTERNAL proga,progb
end subroutine
```

but this does not:
```fortran
subroutine test6(proga,progb)
external PROGA,PROGB
end subroutine
```

Have tested with fcm-2014.12.0, fcm-2014.09.0, fcm-2014-03.

Matt, will email you a `.tgz` of the test cases I used as I can't upload it here.

**Comment by matthewrmshin** [comment]
Looks like the symbols for the arguments are not made case-insensitive.

**Comment by gdcarver** [comment]
Thanks Matt. I've added the bugfix and it confirmed it works.
