### ISSUE TITLE
fcm-add-trac-env: group read permission 

### ISSUE THREAD

**Issue by benfitzpatrick** [metomi/fcm#184]
We have needed to run `chmod g+r conf/trac.ini` for Apache to be able to read a new
Trac project's configuration file. `fcm-add-trac-env` should sort this out.

**Comment by matthewrmshin** [comment]
I believe this has already been fixed by #129. The `_chgrp_and_chmod` function in `FCM::Admin::System` appears to do the right thing on HEAD of master.
