### ISSUE TITLE
fcm make: unable to relocate dest due to absolute paths in ctx.gz

### ISSUE THREAD

**Issue by MartinDix** [metomi/fcm#185]
We have shared directories on both our front end and HPC machines where we'd like to keep UM prebuilds. Because of the way permissions are set up it's difficult to write to these with a normal fcm make.The preferred approach would be to create the prebuild as a regular user and then move the prebuild directories to the shared areas.

However moving prebuilds doesn't seem to work. A make using the prebuild still tries to access files from the original location. The problem seems to be the full file paths for the extract and cache directories in .fcm_make/ctx.gz.

My perl isn't up to properly understanding the storable data structure, but if I do a brute force string replace of the path names in this file (and fix the string length headers) then I get something that works. (Our HPC system is down for maintenance today so I got further into this than I really intended)

```python
import gzip
f = gzip.open('ctx.gz', 'rb')
data = f.read()
f.close()

old_path = '/home/user/prebuild'
new_path = '/home/shared/prebuild'

newdata = data.replace(old_path, new_path)
# Now fix up all the string lengths
delta = len(new_path) - len(old_path)
# Strings don't support item assignment so use an array
b = bytearray(newdata)
start = 0
pos = newdata.find(new_path,start)
while pos > 0:
    b[pos-1] += delta
    start = pos + 1
    pos = newdata.find(new_path,start)

f = gzip.open('newctx.gz', 'wb')
f.write(str(b))
f.close()
```

Is there some more elegant way around this? I'm using 2015.03.0. I was hopeful when I saw the comment in the release notes "This should make it easier to relocate a build" but it hasn't helped this problem.

**Comment by matthewrmshin** [comment]
Looks like build system also stores absolute paths.
