### ISSUE TITLE
fcm commit: use commit without editor

### ISSUE THREAD

**Issue by Dong-ilJang** [metomi/fcm#202]
Hi, my name is Dong-il Jang at KMA.

Do you have a plan to support '--message' or '--file' options like subversion commit?

KMA has to keep two servers for double-step mirroring of science repository for the security policy.
Intranet server (run as a gateway (login server) to HPC) can not connect science repository directly.
Outer server in DMZ can connect science repository directly and intra server.

When KMA staffs try to commit, we must use two servers like this way.
 - Check out branch on outer server in DMZ on firewall.
 - Copy working copies from outer server to intra server.
 - Modify and test codes on intra server.
 - Copy working copies from intra server to outer server.
 - Commit from outer server to science repository.

I want to make remote fcm commit script on intra server.
But, I found a problem. fcm could not use commit without editor.

How I make remote fcm commit if do not have a plan to support '--message' or '--file' options?

Regards,
Jang.

**Comment by matthewrmshin** [comment]
Hi @Dong-ilJang Can we discuss this off line via email so we can understand more about the set up at your site? Please use the usual FCM Team email address to contact us. (I don't know your email address, or I would have emailed you instead.)

(FCM Team's email address can be found on this page http://metomi.github.io/fcm/doc/etc/fcm-terms-of-use.html)

**Comment by Dong-ilJang** [comment]
Thank you for your advice.
This is a invalid issue.
