### ISSUE TITLE
fcm make - how to mirror all?

### ISSUE THREAD

**Issue by magdalenagruziel** [metomi/fcm#206]
hi there,

i am still a complete beginner to fcm.
I would like to run fcm_make task remotely
using mirror.target keywords.

To test this I use the rose tutorial exmaple with 'navigate' job.

Anyway, when run locally everything works fine.
The source code gets compiled/built and .exe created.
But when I write in the fcm_make/fcm-make.cfg file
sth like:
==
steps: mirror
mirror.target: some_user@my-remote-host: $HOME/cylc-run/$ROSE_SUITE_NAME/share/$ROSE_TASK_NAME
mirror.prop{config-file.steps} = build
[.. some build options]
==
no .exe gets created, although the src file gets transferred
to the remote machine, and the fcm_make task finishes
with status 'succeeded'.

However, the exact command 'fcm make' is not issued..

We're using cylc-6.1.1, fcm-2014.11.0 and rose-2014.11.1.

What am I missing here?

[as a matter of fact, adding the scirpting commands 'fcm ake'
to the rose suite.rc file performs the task. but I understood
that it should not be necessary? that the proper fcm..cfg 
tackles the fcm make]

I would be very grateful for some hints.
magdalena

**Comment by matthewrmshin** [comment]
I am closing this issue, as it appears to be a request for user support for using FCM in Rose and cylc, and does not appear to be a bug report or enhancement request for the FCM software.

@magdalenagruziel I recommend that you send us an email using the email address documented at [FCM: Terms of Use > FCM: Maintenance](http://metomi.github.io/fcm/doc/etc/fcm-terms-of-use.html#team), so we can discuss your usage off line. Please send us detail of your suite, etc.
