### ISSUE TITLE
Blank variable behaviour

### ISSUE THREAD

**Issue by gdcarver** [metomi/fcm#220]
There is a problem with variables declared with an empty string:

`$LIB=""`

A blank appears in the link line generating an error from gfortran.

Consider this fcm-make.cfg:

```
steps = build
build.source = $HERE/src
dest = $HERE/bin
#  Test 1
$LIB = -lblas
#  Test 2
$LIB = "-llapack"
#  Test 3
$LIB =
#  Test 4
$LIB = ""
build.target=master.exe
build.prop{fc.flags-ld} = $LIB
```

The first 2 tests behave as expect, generating the equivalent link lines:
1. `[info] shell(0  0.0) gfortran -obin/master.exe o/master.o -lblas`
2. `[info] shell(0  0.0) gfortran -obin/master.exe o/master.o -llapack`

The 3rd test, redefines `LIB` as a blank variable and works as expected:
3. `[info] shell(0  0.0) gfortran -obin/master.exe o/master.o`

The 4th test however, fails and puts space into the link line causing gfortran to complain:

```
 [FAIL] gfortran -obin/master.exe o/master.o  # rc=1
 [FAIL] gfortran: error: : No such file or directory
```

The 'no such file or directory' message is referring to the space between the two colons. The link line generated by FCM shows an additional space. It's not clear to me why gfortran should treat this space as a file but it does. I checked the log file and it shows a hex code of x20.

Test 3 & 4 should give behave the same?

Tar file attached with the above test and the log files from each test.
[fcm-var-test.zip](https://github.com/metomi/fcm/files/119479/fcm-var-test.zip)

  Thanks,  Glenn

**Comment by matthewrmshin** [comment]
It is likely that case 3 is parsed and split into an empty array, where as case 4 is parsed and split into a one-element array with an empty string as element 0. The array is then used to build the command array, before being pass to open3.

In case 3, the command would effectively become: `'gfortran' '-obin/master.exe' 'o/master.o'`.

In case 4, the command would effectively become: `'gfortran' '-obin/master.exe' 'o/master.o' ''`.

I'll take a look at this on Monday to confirm.

**Comment by matthewrmshin** [comment]
This comes from the behaviour of the `shellwords` function of the standard Perl module `Text::ParseWords`:

With a `""` string:

```perl
use Data::Dumper;
use Text::ParseWords qw{shellwords};
warn(Dumper([shellwords(q{""})]));
```

You get:

```perl
$VAR1 = [
          ''
        ];
```

With an empty string:

```perl
use Data::Dumper;
use Text::ParseWords qw{shellwords};
warn(Dumper([shellwords(q{})]));
```

You get:

```perl
$VAR1 = [];
```

**Comment by matthewrmshin** [comment]
@gdcarver I am a bit reluctant to change the logic here. The current logic does allow you to specify, on very rare occasion, a blank argument in a command. Is there any reason why users need to do `$LIB=""` instead of `$LIB=`?

(A bit unrelated, instead of using `build.prop{fc.flags-ld}`, you can use the `build.prop{fc.libs}` property to declare a list of link libraries, e.g. `build.prop{fc.libs} = blas lapack` in your example. A pair of `""` in such a declaration will still cause a failure, unfortunately.)

**Comment by gdcarver** [comment]
@matthewrmshin no reason why `$LIB=""` instead of `$LIB=`, though obviously it needs to be used with care as it can generate (confusing) failure messages.

(On `fc.libs .v. fc.flags-ld`, our system modules set an env variable e.g `GRIB_API_LIBS=-L/usr/local/apps -Wl,-rpath ... -lgrib_api ...`, making it easier to use `fc.flags-ld` rather than split the env var to use in `fc.libs, fc.lib-paths & fc.flags-ld`. Unless I've misunderstood.)

Feel free to close this issue.

**Comment by sunt05** [comment]
happened to undergo the same issue when compiling a library in a manylinux docker image and couldn't find why.
great to see this post! and now have better/correct understanding of our situation.

**Comment by sunt05** [comment]
just resolve this issue by replacing a blank linking flag `""` in  `"gfortran" ".... many objects ..." "-o target" ""` by `"-v"`, which is unnecessary but harmless: as I need to trigger this gfortran from a python `setup.py` file for multiple platforms and those other than manylinux need a `-static` flag.
