### ISSUE TITLE
fcm-make: Doesn't handle "module function" construct correctly

### ISSUE THREAD

**Issue by scwhitehouse** [metomi/fcm#255]
Since #253 went on master, fcm-make hasn't handled the Fortran `module function` construct correctly. The error is:

```
[FAIL] function.mod: target not found after an update:
[FAIL] /var/tmp/fruw-6130919/fcm_make2_um2lfric_meto-x86-gfortran-gcc_safe.1.trunkdRhG5CF/build/include/function.mod: expect target file
[FAIL] compile+   0.0 ! function.mod         <- lfric/infrastructure/source/solveriterative_solver_mod.F90
[FAIL] ! function.mod        : update task failed

```
To me this looks like fcm-make is treating `module function` as a module named "function" rather than interpreting both together.

For an example, see:
https://github.com/metomi/fab/blob/master/TestCases/FortranSubmodule/class_mod.f90

**Comment by matthewrmshin** [comment]
Do we have more examples of similar Fortran 2008+ constructs to support?

**Comment by matthewrmshin** [comment]
Just been told by @scwhitehouse and @stevewardle that https://github.com/metomi/fab/tree/master/TestCases/FortranSubmodule may be a good starting point.
